# Generated by Django 3.2.13 on 2024-01-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_dsh', '0003_testc'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestb',
            name='field1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicaltestb',
            name='field10',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='historicaltestb',
            name='field2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicaltestb',
            name='field3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicaltestb',
            name='field4',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicaltestb',
            name='field5',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicaltestb',
            name='field6',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historicaltestb',
            name='field7',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicaltestb',
            name='field8',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaltestb',
            name='field9',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testb',
            name='field1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testb',
            name='field10',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='testb',
            name='field2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testb',
            name='field3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testb',
            name='field4',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='testb',
            name='field5',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='testb',
            name='field6',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testb',
            name='field7',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='testb',
            name='field8',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='testb',
            name='field9',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
