# Generated by Django 4.2.7 on 2024-01-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_dsh', '0006_historicaltestc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltestc',
            old_name='name',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='testc',
            old_name='name',
            new_name='id',
        ),
    ]
